version: "3.8"
name: api-crud
services:
  mysql:
    container_name: mysql
    image: mysql:8.3
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: hackathon_api